#!/usr/bin/env bash 
#superstitious

i=1

while [ $i -le 20 ]
do
echo "$1"
case $1 in
	"4") echo "bad luck from China"
	;
	"9") echo "bad luck from Japan"
	;
	"17") echo "bad luck from Italy"
	;
esac
((1++))
done
